// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.26.1
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CromPlugin_GetManifest_FullMethodName   = "/cromcloud.CromPlugin/GetManifest"
	CromPlugin_HealthCheck_FullMethodName   = "/cromcloud.CromPlugin/HealthCheck"
	CromPlugin_ExecuteAction_FullMethodName = "/cromcloud.CromPlugin/ExecuteAction"
	CromPlugin_GetUI_FullMethodName         = "/cromcloud.CromPlugin/GetUI"
)

// CromPluginClient is the client API for CromPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CromPlugin é o serviço que TODO plugin deve implementar.
type CromPluginClient interface {
	// Retorna informações sobre o plugin (metadados do manifest).
	GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Manifest, error)
	// Health check — verifica se o plugin está vivo.
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// Executa uma ação do plugin.
	ExecuteAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Retorna os dados/assets de UI do plugin (Schema JSON ou Iframe HTML)
	GetUI(ctx context.Context, in *UIRequest, opts ...grpc.CallOption) (*UIResponse, error)
}

type cromPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewCromPluginClient(cc grpc.ClientConnInterface) CromPluginClient {
	return &cromPluginClient{cc}
}

func (c *cromPluginClient) GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Manifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manifest)
	err := c.cc.Invoke(ctx, CromPlugin_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cromPluginClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CromPlugin_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cromPluginClient) ExecuteAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, CromPlugin_ExecuteAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cromPluginClient) GetUI(ctx context.Context, in *UIRequest, opts ...grpc.CallOption) (*UIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UIResponse)
	err := c.cc.Invoke(ctx, CromPlugin_GetUI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CromPluginServer is the server API for CromPlugin service.
// All implementations must embed UnimplementedCromPluginServer
// for forward compatibility.
//
// CromPlugin é o serviço que TODO plugin deve implementar.
type CromPluginServer interface {
	// Retorna informações sobre o plugin (metadados do manifest).
	GetManifest(context.Context, *Empty) (*Manifest, error)
	// Health check — verifica se o plugin está vivo.
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	// Executa uma ação do plugin.
	ExecuteAction(context.Context, *ActionRequest) (*ActionResponse, error)
	// Retorna os dados/assets de UI do plugin (Schema JSON ou Iframe HTML)
	GetUI(context.Context, *UIRequest) (*UIResponse, error)
	mustEmbedUnimplementedCromPluginServer()
}

// UnimplementedCromPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCromPluginServer struct{}

func (UnimplementedCromPluginServer) GetManifest(context.Context, *Empty) (*Manifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedCromPluginServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCromPluginServer) ExecuteAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedCromPluginServer) GetUI(context.Context, *UIRequest) (*UIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUI not implemented")
}
func (UnimplementedCromPluginServer) mustEmbedUnimplementedCromPluginServer() {}
func (UnimplementedCromPluginServer) testEmbeddedByValue()                    {}

// UnsafeCromPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CromPluginServer will
// result in compilation errors.
type UnsafeCromPluginServer interface {
	mustEmbedUnimplementedCromPluginServer()
}

func RegisterCromPluginServer(s grpc.ServiceRegistrar, srv CromPluginServer) {
	// If the following call panics, it indicates UnimplementedCromPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CromPlugin_ServiceDesc, srv)
}

func _CromPlugin_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CromPluginServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CromPlugin_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CromPluginServer).GetManifest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CromPlugin_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CromPluginServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CromPlugin_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CromPluginServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CromPlugin_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CromPluginServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CromPlugin_ExecuteAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CromPluginServer).ExecuteAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CromPlugin_GetUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CromPluginServer).GetUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CromPlugin_GetUI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CromPluginServer).GetUI(ctx, req.(*UIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CromPlugin_ServiceDesc is the grpc.ServiceDesc for CromPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CromPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cromcloud.CromPlugin",
	HandlerType: (*CromPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _CromPlugin_GetManifest_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _CromPlugin_HealthCheck_Handler,
		},
		{
			MethodName: "ExecuteAction",
			Handler:    _CromPlugin_ExecuteAction_Handler,
		},
		{
			MethodName: "GetUI",
			Handler:    _CromPlugin_GetUI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
